### ISSUE TITLE
Game continues to play behind gameover/info modal. Are we worried?

### ISSUE THREAD

**Issue by DaveyJH** [Abibubble/icecapades#92]

**Comment by Abibubble** [comment]
Links with replay modal issue

**Comment by DaveyJH** [comment]
Sorry, didn't realise this would all come through to you!! Sorry its late. I am done for now
-------- Original message --------From: Abi Harrison ***@***.***> Date: 08/08/2021  01:51  (GMT+00:00) To: Abibubble/icecapades ***@***.***> Cc: DaveyJH ***@***.***>, Author ***@***.***> Subject: Re: [Abibubble/icecapades] Game continues to play behind gameover/info modal. Are we worried? (#92) 
Links with replay modal issue
