### ISSUE TITLE
Replay buttons do nothing on gameover modal

### ISSUE THREAD

**Issue by DaveyJH** [Abibubble/icecapades#93]
I assume we need to have a way to restart the game. Clear the entire canvas, all arrays and Tux?
Start with a new instance of Tux? reset health and snowballs

**Comment by Abibubble** [comment]
Yeah, this hasn't been created yet. Part of this could be to pause the game is a modal is showing, linking to the other issue. Then if Replay is chosen, reset all variables

**Comment by Abibubble** [comment]
@manni8436 is currently working on this :)
