### ISSUE TITLE
Jump time/weight of Tux doesn't allow for much error.

### ISSUE THREAD

**Issue by DaveyJH** [Abibubble/icecapades#95]
- Should we reduce Tux' weight to slow down his fall rate
- Should we increase the vy increase to make him jump higher
- Maybe scale him down by 10% or so

**Comment by Abibubble** [comment]
I like this plan, also maybe reducing the hit box size to better fit Tux?

**Comment by Abibubble** [comment]
Game speed seems different on different machines - Dave was able to jump worms at 0.5 tux.weight, I couldn't jump them even at 0.3
